Make error case messages more clear

diff --git a/bin/rfdocker b/bin/rfdocker
--- a/bin/rfdocker
+++ b/bin/rfdocker
@@ -9,17 +9,27 @@ rf_version=$(cat "$this_path/../rf_version")
 
 ### main #######################################################################
 
+if [ -z "$TESTS_PATH" ]; then
+  echo "[rfdocker] Error: Set 'TESTS_PATH' to where 'tests/' is found, e.g.:"
+  echo ""
+  echo "TESTS_PATH=../tests/ $0 $@"
+  exit 64
+fi
+
+tests_path="$(cd "$TESTS_PATH" && pwd)"
+
 if [ -z "$RESULTS_PATH" ]; then
-  echo -e "[rfdocker] Variable 'RESULTS_PATH' is not explicitly set for outputs"
-  echo -e "[rfdocker] -> assuming $this_path/results/ \n"
+  echo "[rfdocker] Variable 'RESULTS_PATH' is not explicitly set for outputs"
+  echo "[rfdocker] -> assuming $this_path/results/"
+  echo ""
   results_path="$this_path/results"
 else
   results_path="$(cd "$RESULTS_PATH" && pwd)"
 fi
 
-# Exit with non-zero, due to set -e, if TESTS_PATH is not set
-set -u
-tests_path="$(cd "$TESTS_PATH" && pwd)"
+echo "[rfdocker] Using local Docker image 'rfdocker:$rf_version'"
+echo "[rfdocker] Ensure you have built this with $this_path../scripts/build.sh"
+echo ""
 
 docker run --rm -ti \
   -e UNAME="robot" \
